services:
  kali:
    build: .
    volumes:
      - kali-data:/home/kali
      - ./tryhackme.ovpn:/home/kali/tryhackme.ovpn:rw
      - ./.tmux.conf:/home/kali/.tmux.conf:ro
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "5905:5901"
    environment:
      - TZ=Asia/Tokyo

volumes:
  kali-data:

